In [1]:
import pandas as pd
import numpy as np
import re

#import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

from collections import Counter

In [2]:
# nltk.download()

In [3]:
violations_section = pd.read_csv("../data/violations_section.csv")
violations_TCA = pd.read_csv("../data/violations_TCA.csv")
violations_MCL = pd.read_csv("../data/violations_MCL.csv")
violations_description_id = pd.read_csv("../data/violations_description_id.csv")
violations_remainder = pd.read_csv("../data/violations_remainder.csv")

In [4]:
violations_list = [violations_section, violations_TCA, violations_MCL, violations_description_id, violations_remainder]

In [5]:
for violation in violations_list:
    assert 'Unnamed: 0' in violation.columns

In [6]:
for violation in violations_list:
    violation.set_index('Unnamed: 0', inplace=True)
    violation.index.rename('Original_Index', inplace=True)

In [7]:
violations_description_id.head()

,id,type,desc,text,remedial
Original_Index,,,,,
15,(B). It is unlawful for any person to dispose ...,NaN,N,NaN,1.0
438,he or she shall serve notice of the risk and t...,NaN,NaN,NaN,NaN
439,tree at the expense of the property owner,NaN,N,NaN,2.0
707,"human occupation or use, upon failure or refus...",NaN,NaN,NaN,NaN
708,"remove or demolish, such dwelling or structure...",NaN,N,NaN,2.0

In [8]:
violations_description_id['text'] = violations_description_id['id'].values

In [9]:
violations_description_id.head()

,id,type,desc,text,remedial
Original_Index,,,,,
15,(B). It is unlawful for any person to dispose ...,NaN,N,(B). It is unlawful for any person to dispose ...,1.0
438,he or she shall serve notice of the risk and t...,NaN,NaN,he or she shall serve notice of the risk and t...,NaN
439,tree at the expense of the property owner,NaN,N,tree at the expense of the property owner,2.0
707,"human occupation or use, upon failure or refus...",NaN,NaN,"human occupation or use, upon failure or refus...",NaN
708,"remove or demolish, such dwelling or structure...",NaN,N,"remove or demolish, such dwelling or structure...",2.0

In [10]:
for violation in violations_list:
    violation.drop('id', axis='columns', inplace=True)
    
    violation['desc'].replace(np.nan, '', regex=True, inplace=True)
    violation['text'].replace(np.nan, '', regex=True, inplace=True)

In [11]:
violations_section.head()

,type,desc,text,remedial
Original_Index,,,,
0,BANNERS,Banners,Section 17.32.060 & 17.32.070 - Banners: Bann...,CAAZ_BANNERS
1,BGMATOWNER,Proper Maintenance Req - Owner,Section 16.16.030 (B) - Proper maintenance req...,CAAH_BG_MATOWNER
2,BLDGMAINT,Proper Maintenance Req,Section 16.16.030 (A) - Proper maintenance req...,CAAH_BLDG_MAINT
3,BLDGPERMIT,Building Permit Required,Section 16.28.010 - Building Permit Required: ...,CAAB_BLDG_PERMIT
4,BLDGSCOPE,Scope of Building Code,Section 16.16.020 (B) - The provisions of this...,CAAH_BLDG_SCOPE

In [12]:
#violation_section_removed = re.sub(r"(S|s)ection\s*(\d+)\.(\d+)\.(\d+)", '', string)

In [13]:
violations_TCA.head()

,type,desc,text,remedial
Original_Index,,,,
106,LANDREG,Landlord Registration Required,Tennessee Code Annotated (TCA) 66-28-101 - Fai...,CAAR_LAND_REG
376,CAAR_LAND_REG,LANDLORD REGISTRATION REQUIRED,Tennessee Code Annotated (TCA) 66-28-101 - Fai...,NaN
807,BT575101A2,Not Manufacturer and Wholesale Retail,T.C.A 57-5-101(a)(2): Except as otherwise prov...,NaN
808,BT575101A3,Not Wholesale and Manufacturer Retail,T.C.A 57-5-101(a)(3): Except as otherwise prov...,NaN
809,BT575103A1,Operating without county city permit,T.C.A 57-5-103(a)(1): It is unlawful to operat...,NaN

In [14]:
#"(T.C.A|Tennessee Code Annotated)"

In [15]:
violations_MCL.head()

,type,desc,text,remedial
Original_Index,,,,
481,CAGA_DEX,DOG EXCREMENT,MCL Chapter 8.04.180 – Removal of Excrement. ...,NaN
482,CAGB_HAZ_W,HAZARDOUS WASTE,"MCL Chapter 10.20.150 - Hazardous, pathogenic ...",NaN
483,CAGC_GCL,GARBAGE CONTAINER LIDS,MCL Chapter 10.20.160 – Container Requirements...,NaN
484,CAGD_ID,ILLEGAL DUMPING,MCL Chapter 10.20.320 – Illegal Dumping. It i...,NaN
485,CAGE_LPR,LITTER ON PRIVATE PROPERTY,MCL Chapter 10.24.070 - Litter on private prop...,NaN

In [16]:
#"(M.C.L|MCL Chapter)"

In [17]:
violations_description_id.head()

,type,desc,text,remedial
Original_Index,,,,
15,NaN,N,(B). It is unlawful for any person to dispose ...,1.0
438,NaN,,he or she shall serve notice of the risk and t...,NaN
439,NaN,N,tree at the expense of the property owner,2.0
707,NaN,,"human occupation or use, upon failure or refus...",NaN
708,NaN,N,"remove or demolish, such dwelling or structure...",2.0

In [18]:
violations_remainder.head()

,type,desc,text,remedial
Original_Index,,,,
126,MVENVEND,Mobile Vending,Ordinance BL2006-1283 - Mobile Vendor: The ped...,CAAZ_MVEN_VENDING
196,TRASHCANS,Trash Cans,Ordinance 89-826 - Trash Cans: Refuse containe...,CAAH_TRASH_CANS
209,SWVIOLPTP,Violations - Post Construction Treatment,See SW Code,NaN
210,SWVIOLWQ,Violations for Water Quality Impacts,See SW Code,NaN
211,SWENVCRT,Environmental Court Proceedings,See SW Code,NaN

In [19]:
master_violations = pd.concat(violations_list)

In [20]:
master_violations.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 809 entries, 0 to 933
Data columns (total 4 columns):
type        788 non-null object
desc        809 non-null object
text        809 non-null object
remedial    220 non-null object
dtypes: object(4)
memory usage: 31.6+ KB

In [21]:
master_violations.head()

,type,desc,text,remedial
Original_Index,,,,
0,BANNERS,Banners,Section 17.32.060 & 17.32.070 - Banners: Bann...,CAAZ_BANNERS
1,BGMATOWNER,Proper Maintenance Req - Owner,Section 16.16.030 (B) - Proper maintenance req...,CAAH_BG_MATOWNER
2,BLDGMAINT,Proper Maintenance Req,Section 16.16.030 (A) - Proper maintenance req...,CAAH_BLDG_MAINT
3,BLDGPERMIT,Building Permit Required,Section 16.28.010 - Building Permit Required: ...,CAAB_BLDG_PERMIT
4,BLDGSCOPE,Scope of Building Code,Section 16.16.020 (B) - The provisions of this...,CAAH_BLDG_SCOPE

In [22]:
desc_list = master_violations["desc"].tolist()
#desc_list

lower = [t.lower() for t in desc_list]
#lower

one_string = ' '.join(lower)
#one_string

tokens = [w for w in word_tokenize(one_string)
          if w.isalpha()]
#tokens

no_stop = [word for word in tokens if word not in stopwords.words('english')]
#no_stop

a = dict(Counter(no_stop))
#a

s = pd.Series(a, name="freq")

another_test = pd.DataFrame(data = s, columns = ["freq"])
another_test = another_test.reset_index()
another_test.columns = ["kw", "freq"]
another_test.head()

          kw  freq
0  abandoned     2
1   accepted     1
2      acces     2
3     access     4
4  accessory     1

In [23]:
another_test_sorted = another_test.sort_values(by = "freq", ascending = False)
another_test_sorted

                kw  freq
242       exterior   111
51              bb    51
32            area    46
59           bldgs    44
530           prop    44
747          water    36
491         permit    34
566       required    32
71       buildings    31
529     prohibited    27
285        garbage    26
447      occupancy    26
638          signs    25
636           sign    21
686         system    20
266           fire    19
503       plumbing    19
210     electrical    18
54            beer    16
596        rubbish    15
602         safety    15
353       interior    15
663        storage    14
604           sale    14
245     facilities    14
605          sales    14
736    ventilation    13
163      defective    13
478        parking    12
436              n    12
..             ...   ...
197          draft     1
544        rafters     1
576    restriction     1
201          drugs     1
542        quality     1
203           duct     1
540           pump     1
539       publicly     1
537       provided     1
207          eaves     1
553     regulation     1
554    regulations     1
555       released     1
556         relief     1
574    responsbile     1
572       resident     1
368           keys     1
180           disp     1
181       dispense     1
568       requires     1
185      disrepair     1
564         reqmts     1
415           meet     1
562  reproductions     1
188    distributed     1
327          holes     1
190       district     1
191  documentation     1
557       relocate     1
367           kept     1

[776 rows x 2 columns]